// User Actions
export const SET_USER = "SET_USER";
export const TOGGLE_AUTHENTICATING = "TOGGLE_AUTHENTICATING";
export const LOGOUT_USER = "LOGOUT_USER";

// Videos Actions
export const SET_RELATED_VIDEOS = "SET_VIDEOS";
export const TOGGLE_RELATED_VIDEOS_FETCHING = "TOGGLE_VIDEOS_FETCHING";
export const SET_TRENDING_VIDEOS = "SET_TRENDING_VIDEOS";
export const TOGGLE_TRENDING_VIDEOS_FETCHING =
	"TOGGLE_TRENDING_VIDEOS_FETCHING";
export const SET_PLAY_VIDEO = "SET_PLAY_VIDEO";
export const TOGGLE_PLAY_VIDEO_FETCHING = "TOGGLE_PLAY_VIDEO_FETCHING";
export const SET_COMMENTS = "SET_COMMENTS";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const TOGGLE_SEARCH_RESULTS = "TOGGLE_SEARCH_RESULTS";
export const SET_RECOMENDED_VIDEO = "SET_RECOMENDED_VIDEO";
export const TOGGLE_RECOMENDED_VIDEO_FETCHING =
	"TOGGLE_RECOMENDED_VIDEO_FETCHING";
// Channel Actions

export const SET_CHANNLE = "SET_CHANNLE";
export const TOGGLE_CHANNEL_FETCHING = "TOGGLE_CHANNEL_FETCHING";

// Playlist actions

export const SET_PLAYLIST = "SET_PLAYLIST";
export const TOGGLE_PLAYLIST_FETCHING = "TOGGLE_PLAYLIST_FETCHING";

// Subscription actions

export const SET_SUBSCRIPTION = "SET_SUBSCRIPTION";
export const TOGGLE_SUBSCRIPTION_FETCHING = "TOGGLE_SUBSCRIPTION_FETCHING";
